### ISSUE TITLE
Use dependencies instead of devDependencies for deep mode

### ISSUE THREAD

**Issue by mainfraame** [sebastian-software/preppy#24]
First off, absolutely love this library. I’ve created many private node modules for work and I’ve always used either Babel cli directly or a shell script to perform the same thing Preppy does. This library is a far superior replacement; it’s like the webpack for node modules for me...

I was wondering why deep mode doesn’t use the dependencies instead of devDependencies. According to the package.json spec, dependencies are those that will be installed when installing your package into another package.  This also causes potential issues when you have (for instance) rimraf as a dev dependency, but you’re packing a client side package.

Maybe I’m missing something, but I’d like some more insight into this choice...

🙏

**Comment by swernerx** [comment]
"dependencies" will be relevant when the package is installed by others later. Why I use "devDependencies" is because these are not relevant for the users of the package. Actually it would be helpful to have another list of packages dependencies (requirements of the library for the user), devDependencies (tooling for author), bundleDependencies (libraries to bundle). Unfortunately we do not have that... also: for my packages it worked pretty fine. It's not that Preppy is bundling all devDependencies but only the ones which are references by the code. Deep mode basically produces self-contained libraries with no or minimal dependency lists. Often times these only contain modules with native-code parts (Node-GYP powered, ...)

**Comment by swernerx** [comment]
Closing this as no further feedback came along.
